service: rustybeer
provider:
  name: aws
  runtime: rust
  memorySize: 512
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'eu-west-1'}
  tags:
    app: rustybeer
  endpointType: REGIONAL

package:
  individually: true

plugins:
  - serverless-rust
  - serverless-openapi-documentation-v2

custom:
  documentation: ${file(serverless.doc.yml):documentation}

functions:
  abv:
    handler: abv
    description: Calculates ABV from original and final gravities
    events:
      - http:
          path: abv
          method: post
          documentation: ${file(serverless.doc.yml):endpoints.abv}
          request:
            headers:
              Content-Type: true
              schema:
                application/json: ${file(models/AbvRequest.json)}
  dilution:
    handler: dilution
    description: Calculates new gravity after wort dilution
    events:
      - http:
          path: dilution
          method: post
          documentation: ${file(serverless.doc.yml):endpoints.dilution}
          request:
            headers:
              Content-Type: true
              schema:
                application/json: ${file(models/DilutionRequest.json)}
